### ISSUE TITLE
Sample Characterizer Bug Report List and Feature Request

### ISSUE THREAD

**Issue by cltschirhart** [afylab/LabRAD-nSOT-Scanner#2]
**Bug report:**
Fix linecut axis labels
Fix bug thrown when moving linecut lines before there's data
Fix updating of magnetic field value of linecut when in show latest linecut mode
Fix units of delay in four terminal measurement tab (Have it be in seconds to take advantage of the way numbers are formatted, then convert it as required when putting it in the buffer ramp function)
Delete the extra tab which has the connect labrad button, which is now no longer necessary

**Feature request:**
In four terminal magnetic field scan window, have the horizontal line cut plot be horizontal as it is now, but move the version line cut to be on the left or right of the 2D plot and be vertical
Make magnetic field the y axis 

**Very low priority fixes:**
Make things expand in appropriate ratios. In particular, the images at the top right of each tab, the start sweep buttons, the labeled that say the current voltage (or say sweeping) at the top right of the module
When auto level is off, stop from changing range of histogram

**Comment by Raykamakoto** [comment]
Fix units of delay in four terminal measurement tab (Have it be in seconds to take advantage of the way numbers are formatted, then convert it as required when putting it in the buffer ramp function)

fixed by changing label units to (s) and add a multiplier of 1000000 to the buffer ramps

**Comment by Raykamakoto** [comment]
Delete the extra tab which has the connect labrad button, which is now no longer necessary

Deleted the tab

**Comment by Raykamakoto** [comment]
Fix updating of magnetic field value of linecut when in show latest linecut mode

A quick fix

**Comment by Raykamakoto** [comment]
Fix bug thrown when moving linecut lines before there's data

Fixed by not allow connection from moving the line to change the value before sweep

**Comment by Raykamakoto** [comment]
Fix linecut axis labels

**Comment by Raykamakoto** [comment]
In four terminal magnetic field scan window, have the horizontal line cut plot be horizontal as it is now, but move the version line cut to be on the left or right of the 2D plot and be vertical
Make magnetic field the y axis

Done

**Comment by Raykamakoto** [comment]
The only thing left i8s the When auto level is off, stop from changing range of histogram

**Comment by Raykamakoto** [comment]
Feature resolved
